#!/bin/bash

clear
red=`tput setaf 1`
green=`tput setaf 2`
blue=`tput setaf 4`
reset=`tput sgr0`

echo "file: 0--test_0"
echo

commands=(
	#correct comands
	"/bin/ls"
	"ls .."
	"."
	"/"
	"
	"
	"
	"






	"/bin/ls /bin/ls /bin/ls"
	"ls ls ls ls ls ls"
	"ls -la ls -la ls -la"
	"env"
	"env 0"
	"exit"
	"exit 0"
	"exit 98"
	)

for ((i=0; i < ${#commands[@]}; i++))
do 
	echo "[$i]  Command: ${blue}\"${commands[$i]}\" | ../test/run${reset}"
	echo
	echo "->> Esperado <<-"
	echo ${commands[$i]} | /bin/../bin/sh 2>&1

	salida1=$?
	echo
	echo "->> Obtenido <<-"
	echo ${commands[$i]} | ../test/run 2>&1
	salida2=$?

	echo
	if [ "$salida1" -ne "$salida2" ]
	then
		echo "${red}->>>>>>>>>> Error <<<<<<<<<<-"
		echo "Esperado:" $salida1 "<> Obtenido:"  $salida2 "${reset}"
	else
		echo "${green}Esperado: $salida1 <> Obtenido:  $salida2 ${reset}"
	fi
	echo -------------------------------------------
	echo

done

















