#!/bin/bash
# Configuration file

TESTDIR="."
R=$RANDOM
OUTPUTFILE="checker_output_$R"
ERROROUTPUTFILE="checker_error_output_$R"
#SHELL="/home/vagrant/holberton/projects/teams/simple_shell/hsh"
find "$(sudo find /home -type d | grep --regexp="/simple_shell$")" -type f -executable | grep --invert-match ".git" > ./shell_dir 2> /dev/null
SHELL="$(head -1 ./shell_dir)"
#SHELL="/bin/sh"
SLEEP=`which sleep`
SLEEPSECONDS=0.4
LTRACE=`which ltrace`
LTRACEOUTPUTFILE="checker_ltrace_output_$R"
ECHO=`which echo`
CAT=`which cat`
CUT=`which cut`
GREP=`which grep`
WC=`which wc`
RM=`which rm`
TOUCH=`which touch`
CHMOD=`which chmod`

