#!/bin/bash
#
# Empty the PATH and check if /bin/ls still works

command="noexecutable"
tmp_file="checker_tmp_file_$RANDOM"
EXPECT="1: ${command}: Permission denied"


# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# send comman
sudo touch "/usr/local/bin/${command}"
sudo chmod -x "/usr/local/bin/${command}"
sudo chmod +r "/usr/local/bin/${command}"

$ECHO "$command" | $SHELL 2> /dev/stdout > /dev/null | $CUT --fields=2- --delimiter=":" | $CUT --characters=2- > $OUTPUTFILE 2> $ERROROUTPUTFILE &


# wait a little bit
$SLEEP $SLEEPSECONDS


# check the result
nmatch=`$CAT $OUTPUTFILE`
if [ "$nmatch" = "$EXPECT" ]; then
	print_ok
else
	print_ko
	$ECHO -e "    >[\033[31mYour message error\033[37m]";
	$ECHO -e "\t$(cat $OUTPUTFILE)";
	$ECHO -e "    >[\033[32mExpect message error\033[37m]";
	$ECHO -e "\t${EXPECT}";
fi
# clean up
stop_shell
#$RM -f $tmp_file
